"""End-to-end MCP test: spawn the code-graph server over stdio with the official SDK client on the sample apps' combined
graph, list tools, call each one, save the raw outputs to docs/mcp/sample_outputs.md, and assert basic facts.

  .venv/bin/python tests/mcp_e2e.py            (also run by pytest via tests/test_mcp.py)
"""
from __future__ import annotations

import asyncio
import os
import re
import sys
import tempfile
import time
from pathlib import Path

from mcp.client.session import ClientSession
from mcp.client.stdio import StdioServerParameters, stdio_client

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT)); sys.path.insert(0, str(ROOT / "tests"))
from sample import build, PLANS, GATES, EXTRACTOR_DEPS  # noqa: E402

CALLS = [
    ("stats", {}),
    ("search", {"name": "reserve"}),
    ("reaches", {"targets": ["connection:warehouse", "table:warehouse_stock"], "max_per_group": 12}),
    ("reaches", {"targets": ["env:WAREHOUSE_DB_*"], "group_by": "entry_kind"}),
    ("impact", {"method": "StockService::recordSale"}),
    ("siblings", {"symbol": "StockService::reserveLocal", "limit": 6}),
    ("writers", {"table": "books"}),
    ("node", {"id_or_symbol": "App\\Http\\Controllers\\Admin\\InventoryController::index"}),
    ("path", {"source": "page:/", "target": "SalesReportService::remove"}),
    ("downstream", {"target": "page:/reports/:id", "max_per_kind": 10}),
    ("api_calls", {"filter": "unmatched"}),
    ("resolutions", {"concept": "timezone"}),
    ("plan_list", {}),
    ("plan_check", {"name": "preorders", "max_items": 30}),
]


def text_of(res) -> str:
    return "\n".join(getattr(c, "text", "") for c in res.content)


async def run(db: Path, calls=CALLS) -> dict:
    params = StdioServerParameters(command=sys.executable, cwd=str(ROOT), env={**os.environ, "TZ": "UTC"},
                                   args=["-m", "codegraph.mcp_server", "--db", str(db), "--plans", str(PLANS)])
    outs = {}
    async with stdio_client(params) as (read, write):
        async with ClientSession(read, write) as session:
            init = await session.initialize()
            tools = await session.list_tools()
            outs["_server"] = f"{init.server_info.name}"
            outs["_tools"] = [(t.name, (t.description or "").split("\n")[0]) for t in tools.tools]
            for name, args in calls:
                t0 = time.time()
                res = await session.call_tool(name, args)
                outs[f"{name} {args}"] = (text_of(res), round(time.time() - t0, 2), bool(res.is_error))
    return outs


async def run_index_tool() -> str:
    """Exercise the `index` tool against the gating fixture into a temp DB."""
    tmp = Path(tempfile.mkdtemp()) / "fixture.db"
    params = StdioServerParameters(command=sys.executable, cwd=str(ROOT), env={**os.environ, "TZ": "UTC"},
                                   args=["-m", "codegraph.mcp_server", "--db", str(tmp)])
    async with stdio_client(params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            r = await session.call_tool("index", {"root": str(ROOT / "tests" / "gating_fixture"), "gates": str(GATES)})
            r2 = await session.call_tool("stats", {})
            return text_of(r) + "\n" + text_of(r2)


def write_samples(outs: dict, name="sample_outputs.md") -> Path:
    p = ROOT / "docs" / "mcp" / name
    p.parent.mkdir(parents=True, exist_ok=True)
    L = ["# code-graph MCP: sample outputs (real calls via the MCP Python SDK stdio client)", "",
         f"Server: `{outs['_server']}`, DB: combined graph of `examples/bookstore-api` + `examples/bookstore-web`. "
         "Generated by `tests/mcp_e2e.py`; timings are from the machine that generated the file.", "", "## tools/list", ""]
    for n, d in outs["_tools"]:
        L.append(f"- `{n}`: {d}")
    for k, v in outs.items():
        if k.startswith("_"):
            continue
        txt, secs, err = v
        txt = re.sub(r"(?:/[^\s/]+)*/(?:tmp|T)/[^\s/]+/", "<tmp>/", txt.replace(str(ROOT) + "/", ""))
        L += ["", f"## `{k}`  ({secs}s, {len(txt)} chars{', ERROR' if err else ''})", "", "```", txt, "```"]
    p.write_text("\n".join(L) + "\n")
    return p


def check(outs: dict):
    names = {n for n, _ in outs["_tools"]}
    assert {"reaches", "impact", "siblings", "writers", "node", "search", "stats", "index", "downstream", "path",
            "api_calls", "resolutions", "plan_list", "plan_load", "plan_validate", "plan_check", "plan_baseline"} <= names, names
    for k, v in outs.items():
        if not k.startswith("_"):
            assert not v[2], f"tool error: {k}: {v[0][:300]}"
    get = lambda pre: next(v[0] for k, v in outs.items() if k.startswith(pre))  # noqa: E731
    r = get("reaches {'targets': ['connection:warehouse'")
    assert "## RUNTIME" in r and "## GATED" in r and "## OPERATOR" in r
    assert "InventoryController::index" in r.split("## GATED")[1]
    assert "SyncWarehouseCommand::handle" in r.split("## OPERATOR")[1].split("## GATED")[0]
    p = get("path")
    for hop in ("HTTP_CALLS", "MATCHES_ROUTE", "ROUTES_TO", "SalesReportService::remove"):
        assert hop in p, (hop, p)
    rs = get("resolutions")
    assert "DIVERGENCE" in rs and "never sent" in rs and "ReportController::resolveTimezone" in rs
    pc = get("plan_check")
    for frag in ("MISSING FROM PLAN", "Filament\\Resources\\BookResource::form", "UpdateBookRequest::rules",
                 "example/bookstore-mobile", "STILL PRESENT", "#8 [open, NOT LINKED in plan]", "lacks auth:api"):
        assert frag in pc, frag


def run_all() -> dict:
    outs = asyncio.run(run(build()["combined"]))
    outs["index (gating fixture, temp db)"] = (asyncio.run(run_index_tool()), 0, False)
    check(outs)
    assert "gated edges {'new_inventory':" in outs["index (gating fixture, temp db)"][0]
    write_samples(outs)
    return outs


def test_mcp_e2e():
    import pytest
    if not EXTRACTOR_DEPS.exists():
        pytest.skip("run `npm ci` in codegraph/plugins/ts/extractor")
    run_all()


if __name__ == "__main__":
    for k, v in run_all().items():
        if not k.startswith("_"):
            print(f"{k}: {len(v[0])} chars, {v[1]}s, error={v[2]}")
