"""End-to-end MCP test: spawn the code-graph server over stdio with the official SDK client on the sample apps' combined
graph, list tools, call each one, save the raw outputs to docs/mcp/sample_outputs.md, and assert basic facts.

  .venv/bin/python tests/mcp_e2e.py            (also run by pytest via tests/test_mcp.py)
"""
from __future__ import annotations

import asyncio
import json
import os
import re
import sys
import tempfile
import time
from pathlib import Path

from mcp.client.session import ClientSession
from mcp.client.stdio import StdioServerParameters, stdio_client

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT)); sys.path.insert(0, str(ROOT / "tests"))
from sample import build, PLANS, GATES, EXTRACTOR_DEPS, needs_php  # noqa: E402

CALLS = [
    ("stats", {}),
    ("search", {"name": "reserve"}),
    ("search", {"name": "auth"}),
    ("routes", {"writes": "*"}),
    ("routes", {"reaches": ["connection:warehouse"], "unguarded": True}),
    ("routes", {"writes": "books", "missing": "auth:api"}),
    ("reaches", {"targets": ["connection:warehouse", "table:warehouse_stock"], "max_per_group": 12}),
    ("reaches", {"targets": ["env:WAREHOUSE_DB_*"], "group_by": "entry_kind"}),
    ("impact", {"method": "StockService::recordSale"}),
    ("callers", {"symbol": "StockService::reserve"}),
    ("tests_covering", {"target": "StockService::reserve"}),
    ("coverage", {}),
    ("siblings", {"symbol": "StockService::reserveLocal", "limit": 6}),
    ("siblings", {"symbol": "StockService::reserve"}),
    ("writers", {"table": "books"}),
    ("node", {"id_or_symbol": "App\\Http\\Controllers\\Admin\\InventoryController::index"}),
    ("path", {"source": "page:/", "target": "SalesReportService::remove"}),
    ("downstream", {"target": "page:/reports/:id", "max_per_kind": 10}),
    ("api_calls", {"filter": "unmatched"}),
    ("resolutions", {"concept": "timezone"}),
    ("plan_list", {}),
    ("plan_check", {"name": "preorders"}),
    ("plan_check", {"name": "preorders", "details": True, "max_items": 30}),
]


def text_of(res) -> str:
    return "\n".join(getattr(c, "text", "") for c in res.content)


async def run(db: Path, calls=CALLS) -> dict:
    params = StdioServerParameters(command=sys.executable, cwd=str(ROOT), env={**os.environ, "TZ": "UTC"},
                                   args=["-m", "cg_code_graph.mcp_server", "--db", str(db), "--plans", str(PLANS)])
    outs = {}
    async with stdio_client(params) as (read, write):
        async with ClientSession(read, write) as session:
            init = await session.initialize()
            tools = await session.list_tools()
            outs["_server"] = f"{init.server_info.name}"
            outs["_tools"] = [(t.name, (t.description or "").split("\n")[0]) for t in tools.tools]
            for name, args in calls:
                t0 = time.time()
                res = await session.call_tool(name, args)
                outs[f"{name} {args}"] = (text_of(res), round(time.time() - t0, 2), bool(res.is_error),
                                          (res.structured_content or {}).get("completeness"))
    return outs


async def run_index_tool() -> str:
    """Exercise the `index` tool against the gating fixture into a temp DB."""
    tmp = Path(tempfile.mkdtemp()) / "fixture.db"
    params = StdioServerParameters(command=sys.executable, cwd=str(ROOT), env={**os.environ, "TZ": "UTC"},
                                   args=["-m", "cg_code_graph.mcp_server", "--db", str(tmp)])
    async with stdio_client(params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            r = await session.call_tool("index", {"root": str(ROOT / "tests" / "gating_fixture"), "gates": str(GATES)})
            r2 = await session.call_tool("stats", {})
            return text_of(r) + "\n" + text_of(r2)


def stable(txt: str) -> str:
    """Strip machine- and run-specific values: absolute paths, index timestamps, durations."""
    txt = re.sub(r"(?:/[^\s/]+)*/(?:tmp|T)/[^\s/]+/", "<tmp>/", txt.replace(str(ROOT) + "/", ""))
    txt = re.sub(r"\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} UTC", "<indexed_at>", txt)
    txt = re.sub(r"index_seconds=[\d.]+", "index_seconds=<s>", txt)
    return re.sub(r"\bin [\d.]+s\b", "in <s>s", txt)


def write_samples(outs: dict, name="sample_outputs.md") -> Path:
    p = ROOT / "docs" / "mcp" / name
    p.parent.mkdir(parents=True, exist_ok=True)
    L = ["# code-graph MCP: sample outputs (real calls via the MCP Python SDK stdio client)", "",
         f"Server: `{outs['_server']}`, DB: combined graph of `examples/bookstore-api` + `examples/bookstore-web`. "
         "Generated by `tests/mcp_e2e.py`. Volatile values (index timestamps and durations) are replaced by placeholders, "
         "so regenerating the file on unchanged code gives identical bytes.", "", "## tools/list", ""]
    for n, d in outs["_tools"]:
        L.append(f"- `{n}`: {d}")
    for k, v in outs.items():
        if k.startswith("_"):
            continue
        txt, secs, err = v[:3]
        txt = stable(txt)
        L += ["", f"## `{k}`  ({len(txt)} chars{', ERROR' if err else ''})", "", "```", txt, "```"]
        if len(v) > 3 and v[3] is not None:
            L += ["", f"structured `completeness`: `{json.dumps(v[3], sort_keys=True)}`"]
    body = "\n".join(L) + "\n"
    if not p.exists() or p.read_text() != body:  # never touch the file when nothing changed
        p.write_text(body)
    return p


def check(outs: dict):
    names = {n for n, _ in outs["_tools"]}
    assert {"reaches", "impact", "siblings", "writers", "node", "search", "stats", "index", "downstream", "path",
            "api_calls", "resolutions", "plan_list", "plan_load", "plan_validate", "plan_check", "plan_baseline"} <= names, names
    for k, v in outs.items():
        if not k.startswith("_"):
            assert not v[2], f"tool error: {k}: {v[0][:300]}"
            if len(v) > 3:  # every reply carries machine-readable completeness next to the text
                assert isinstance(v[3], dict) and "complete" in v[3] and "languages" in v[3], (k, v[3])
    get = lambda pre: next(v[0] for k, v in outs.items() if k.startswith(pre))  # noqa: E731
    r = get("reaches {'targets': ['connection:warehouse'")
    assert "## RUNTIME" in r and "## GATED" in r and "## OPERATOR" in r
    assert "InventoryController::index" in r.split("## GATED")[1]
    assert "SyncWarehouseCommand::handle" in r.split("## OPERATOR")[1].split("## GATED")[0]
    p = get("path")
    for hop in ("HTTP_CALLS", "MATCHES_ROUTE", "ROUTES_TO", "SalesReportService::remove"):
        assert hop in p, (hop, p)
    rs = get("resolutions")
    assert "DIVERGENCE" in rs and "never sent" in rs and "ReportController::resolveTimezone" in rs
    pc = get("plan_check {'name': 'preorders', 'details'")
    for frag in ("MISSING FROM PLAN", "Filament\\Resources\\BookResource::form", "UpdateBookRequest::rules",
                 "example/bookstore-mobile", "STILL PRESENT", "#8 [open, NOT LINKED in plan]", "lacks auth:api"):
        assert frag in pc, frag
    compact = get("plan_check {'name': 'preorders'}")
    for frag in ("MISSING FROM PLAN", "REVIEW (", "STILL PRESENT", "#8 [open, NOT LINKED in plan]", "lacks auth:api", "details=true"):
        assert frag in compact, frag
    assert len(compact) < len(pc) / 2, (len(compact), len(pc))
    rw = get("routes {'writes': '*'}")
    assert "NO AUTH" in rw and "auth:api" in rw and "DELETE" in rw, rw
    assert "auth:api" in get("search {'name': 'auth'}")
    assert "reserveLocal" in get("siblings {'symbol': 'StockService::reserve'}")
    # replies carry repo-relative paths only
    for k, v in outs.items():
        if not k.startswith("_"):
            assert str(ROOT) not in v[0] and not re.search(r"(?<![\w.~])/(?:tmp|home|workspace|Users|var)/", v[0]), (k, v[0][:400])


def run_all() -> dict:
    outs = asyncio.run(run(build()["combined"]))
    outs["index (gating fixture, temp db)"] = (asyncio.run(run_index_tool()), 0, False)
    check(outs)
    assert "gated edges {'new_inventory':" in outs["index (gating fixture, temp db)"][0]
    write_samples(outs)
    return outs


@needs_php
def test_mcp_e2e():
    import pytest
    if not EXTRACTOR_DEPS.exists():
        pytest.skip("run `npm ci` in cg_code_graph/plugins/ts/extractor")
    run_all()


if __name__ == "__main__":
    for k, v in run_all().items():
        if not k.startswith("_"):
            print(f"{k}: {len(v[0])} chars, {v[1]}s, error={v[2]}")
