"""Generated, copied and vendored files: one classifier (codegraph/core/generated.py) for every walk and the coverage
scan. One fixture per detection source (.gitattributes, each header banner, each path rule, Capacitor webDir, Cordova,
.openapi-generator/FILES, .cg.yaml), the default index without them, `--include-generated` with attrs.generated and
COPY_OF, and the coverage report. Every fixture is written from scratch in a temp dir."""
import json
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from codegraph import config as CFG  # noqa: E402
from codegraph import coverage as C  # noqa: E402
from codegraph import query as Q  # noqa: E402
from codegraph.core import generated as G  # noqa: E402
from codegraph.core.paths import PathRules  # noqa: E402
from codegraph.core.store import GraphStore  # noqa: E402
from codegraph.indexer import index_project  # noqa: E402

HAS_NODE = shutil.which("node") is not None and (ROOT / "codegraph/plugins/ts/extractor/node_modules/typescript").exists()


def write(root: Path, files: dict) -> Path:
    for rel, body in files.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(textwrap.dedent(body).lstrip("\n"))
    return root


def classify(tmp: Path, files: dict, cfg: dict | None = None, include: bool = False) -> G.Classifier:
    root = write(tmp / "p", files)
    clf = G.Classifier(root, cfg, include=include)
    C.scan_tree(root, classifier=clf)
    return clf


def reason(clf: G.Classifier, rel: str):
    h = clf.lookup(rel)
    return (h["kind"], h["reason"]) if h else None


def cg(*args):
    return subprocess.run([sys.executable, "-m", "codegraph.cli", *map(str, args)], cwd=ROOT, capture_output=True, text=True)


# ------------------------------------------------------------------------------------------- header banners
@pytest.mark.parametrize("rel,head,why", [
    ("a.ts", "// @generated by protoc-gen-es v1.10.0\nexport const x = 1\n", "@generated header"),
    ("b.js", "/**\n * @generated SignedSource<<abc>>\n */\nmodule.exports = {}\n", "@generated header"),
    ("c.go", "// Code generated by mockgen. DO NOT EDIT.\npackage foo\n", "'Code generated ... DO NOT EDIT.' header"),
    ("d.dart", "// GENERATED CODE - DO NOT MODIFY BY HAND\npart of 'd_src.dart';\n", "'GENERATED CODE - DO NOT MODIFY BY HAND' header"),
    ("e.cs", "//------------------------------------------------------------------------------\n// <auto-generated>\n"
             "//     This code was generated by a tool.\n// </auto-generated>\nnamespace X {}\n", "<auto-generated> header"),
    ("f.py", "# -*- coding: utf-8 -*-\n# Generated by the protocol buffer compiler.  DO NOT EDIT!\nimport x\n", "protoc / gRPC banner"),
    ("g.py", "# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!\nimport grpc\n", "protoc / gRPC banner"),
    ("h.swift", "// DO NOT EDIT.\n//\n// Generated by the Swift generator plugin for the protocol buffer compiler.\nimport Foundation\n",
     "protoc / gRPC banner"),
    ("i.ts", "/* tslint:disable */\n/**\n * Pet API\n * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).\n"
             " * Do not edit the class manually.\n */\nexport class PetApi {}\n", "OpenAPI Generator banner"),
    ("j.php", "<?php\n/**\n * Generated by: https://openapi-generator.tech\n */\nclass Pet {}\n", "OpenAPI Generator banner"),
    ("k.rb", "# This file is automatically generated by a schema dump.\nmodule K; end\n", "'automatically generated' header"),
    ("l.sh", "#!/bin/sh\n# This file was auto-generated by configure.\necho hi\n", "'automatically generated' header"),
    ("m.swift", "// Generated using Sourcery 2.3.0 — https://github.com/krzysztofzablocki/Sourcery\n// DO NOT EDIT\n\n"
                "// swiftlint:disable all\nimport XCTest\n", "Sourcery banner"),
    ("n.swift", "// swiftlint:disable all\n// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen\n\nimport Foundation\n",
     "SwiftGen banner"),
    ("o.swift", "// Generated by swift-openapi-generator, do not modify.\n@_spi(Generated) import OpenAPIRuntime\n",
     "swift-openapi-generator banner"),
    ("p.swift", "///\n/// @Generated by Mockolo\n///\nimport Foundation\n", "Mockolo banner"),
])
def test_header_banners(tmp_path, rel, head, why):
    root = tmp_path / "p"
    root.mkdir()
    (root / rel).write_text(head)
    assert G.header_marker(root / rel) == why
    clf = G.Classifier(root)
    C.scan_tree(root, classifier=clf)
    assert reason(clf, rel) == ("generated", why)


@pytest.mark.parametrize("head", [
    '"""Mentions @generated and "Code generated by x. DO NOT EDIT." in a docstring."""\nx = 1\n',
    "import os\n# Code generated by x. DO NOT EDIT.\n",                          # after the first line of code
    "const s = '@generated'\n",                                                  # a string, not a comment
    "// Hand-written helpers for the generated client below.\nexport const y = 2\n",
    "",
])
def test_no_banner_no_classification(tmp_path, head):
    p = tmp_path / "x.py"
    p.write_text(head)
    assert G.header_marker(p) is None


# ------------------------------------------------------------------------------------------- path rules
@pytest.mark.parametrize("rel,why", [
    (".nuxt/components.d.ts", "Nuxt build output (.nuxt/)"),
    ("web/.next/server/app.js", "Next.js build output (.next/)"),
    (".svelte-kit/generated/root.js", "SvelteKit build output (.svelte-kit/)"),
    (".output/server/index.mjs", "Nitro / Nuxt build output (.output/)"),
    ("lib/models/user.g.dart", "build_runner output (*.g.dart)"),
    ("lib/models/user.freezed.dart", "freezed output (*.freezed.dart)"),
    ("lib/router.gr.dart", "auto_route output (*.gr.dart)"),
    ("test/api.mocks.dart", "mockito output (*.mocks.dart)"),
    ("lib/generated_plugin_registrant.dart", "Flutter plugin registrant"),
    ("linux/flutter/generated_plugin_registrant.cc", "Flutter plugin registrant"),
    ("macos/Flutter/GeneratedPluginRegistrant.swift", "Flutter plugin registrant"),
    ("ios/Flutter/ephemeral/flutter_lldb_helper.py", "Flutter tool output (ephemeral/)"),
    ("android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java", "Flutter plugin registrant"),
    ("api/v1/user_pb2.py", "protoc output (Python)"),
    ("api/v1/user_pb2_grpc.py", "protoc output (Python)"),
    ("api/v1/user.pb.go", "protoc output (Go)"),
    ("gen/user_pb.ts", "protoc output (TypeScript)"),
    ("Sources/User.pb.swift", "protoc output (Swift)"),
    ("App/Generated/R.generated.swift", "R.swift output"),
    ("src/user.pb.cc", "protoc output (C++)"),
    ("lib/src/user.pbgrpc.dart", "protoc output (Dart)"),
])
def test_path_rules(tmp_path, rel, why):
    clf = classify(tmp_path, {rel: "x = 1\n"})
    assert reason(clf, rel) == ("generated", why)


def test_dist_and_build_are_reported_not_walked(tmp_path):
    clf = classify(tmp_path, {"dist/app.js": "x\n", "build/out.py": "x = 1\n", "src/build/__init__.py": "", "src/main.py": "x = 1\n"})
    g = clf.summary()
    assert set(g["build_dirs"]) >= {"dist", "build"}
    # a source package named build is not generated (every walk already skips the name; the classifier never says so)
    assert clf.lookup("src/build/__init__.py") is None and clf.lookup("src/main.py") is None


# ------------------------------------------------------------------------------------------- .gitattributes
def test_gitattributes_generated_vendored_and_negations(tmp_path):
    clf = classify(tmp_path, {
        ".gitattributes": """
            # api client
            src/api/generated/** linguist-generated=true
            third_party/**       linguist-vendored
            *.min.js             linguist-generated
            src/api/generated/custom.ts -linguist-generated
            src/legacy.ts        linguist-generated=false
            """,
        "src/api/generated/client.ts": "export const c = 1\n",
        "src/api/generated/custom.ts": "export const d = 1\n",
        "src/api/generated/deep/x.ts": "export const e = 1\n",
        "third_party/lib/a.c": "int a;\n",
        "public/vendor.min.js": "x\n",
        "src/legacy.ts": "// @generated\nexport const l = 1\n",     # attribute says hand-written: the banner is ignored
        "src/app.ts": "export const a = 1\n",
    })
    assert reason(clf, "src/api/generated/client.ts") == ("generated", "linguist-generated (.gitattributes)")
    assert reason(clf, "src/api/generated/deep/x.ts") == ("generated", "linguist-generated (.gitattributes)")
    assert clf.lookup("src/api/generated/custom.ts") is None
    assert reason(clf, "third_party/lib/a.c") == ("vendored", "linguist-vendored (.gitattributes)")
    assert reason(clf, "public/vendor.min.js") == ("generated", "linguist-generated (.gitattributes)")
    assert clf.lookup("src/legacy.ts") is None
    assert clf.lookup("src/app.ts") is None


def test_nested_gitattributes_and_unset(tmp_path):
    clf = classify(tmp_path, {
        ".gitattributes": "*.ts linguist-generated\n",
        "pkg/.gitattributes": "keep.ts !linguist-generated\nhand.ts -linguist-generated\n",
        "pkg/gen.ts": "export const g = 1\n",
        "pkg/hand.ts": "export const h = 1\n",
        "pkg/keep.ts": "export const k = 1\n",            # unspecified again: back to detection (no banner)
        "pkg/banner.ts": "// @generated\nexport const b = 1\n",
    })
    assert reason(clf, "pkg/gen.ts")[1] == "linguist-generated (.gitattributes)"
    assert clf.lookup("pkg/hand.ts") is None
    assert clf.lookup("pkg/keep.ts") is None
    assert reason(clf, "pkg/banner.ts")[1] == "linguist-generated (.gitattributes)"


def test_gitattributes_patterns_follow_git():
    rules = G.parse_gitattributes("Api.elm linguist-generated\n/root.ts linguist-generated\nsrc/*.ts linguist-vendored\n"
                                  "docs/ linguist-generated\n\"quoted name\" linguist-generated\n")
    rx = {r.pattern: (k, v) for r, k, v in rules}
    assert len(rules) == 3          # the directory and the quoted pattern are not file patterns
    m = lambda p: [k for r, k, v in rules if r.match(p)]       # noqa: E731
    assert m("Api.elm") == m("a/b/Api.elm") == ["generated"]
    assert m("root.ts") == ["generated"] and m("a/root.ts") == []
    assert m("src/x.ts") == ["vendored"] and m("src/a/x.ts") == []
    assert rx


# ------------------------------------------------------------------------------------------- copy targets
@pytest.mark.parametrize("cfgfile,body", [
    ("capacitor.config.ts", "import { CapacitorConfig } from '@capacitor/cli';\n"
                            "const config: CapacitorConfig = { appId: 'com.example.app', appName: 'Example', webDir: 'dist' };\n"
                            "export default config;\n"),
    ("capacitor.config.js", "module.exports = { appId: 'com.example.app', webDir: \"dist\" }\n"),
    ("capacitor.config.json", '{"appId": "com.example.app", "webDir": "dist"}\n'),
])
def test_capacitor_web_dir_and_copy_targets(tmp_path, cfgfile, body):
    clf = classify(tmp_path, {
        cfgfile: body,
        "src/battery.ts": "export const b = 1\n",
        "android/app/src/main/assets/public/assets/index-abc.js": "x\n",
        "android/app/src/main/assets/public/index.html": "<html></html>\n",
        "android/app/src/main/assets/capacitor.config.json": "{}\n",
        "android/app/src/main/java/com/example/app/MainActivity.java": "class MainActivity {}\n",
        "android/capacitor-cordova-android-plugins/src/main/java/X.java": "class X {}\n",
        "ios/App/App/public/assets/index-abc.js": "x\n",
        "ios/App/App/AppDelegate.swift": "class AppDelegate {}\n",
    })
    h = clf.lookup("android/app/src/main/assets/public/assets/index-abc.js")
    assert h == {"kind": "copied", "reason": "copy of dist/ (Capacitor webDir)", "copy_of": "dist/assets/index-abc.js"}
    assert clf.lookup("ios/App/App/public/assets/index-abc.js")["copy_of"] == "dist/assets/index-abc.js"
    assert reason(clf, "android/app/src/main/assets/capacitor.config.json") == ("generated", "Capacitor sync output")
    assert reason(clf, "android/capacitor-cordova-android-plugins/src/main/java/X.java") == ("generated", "Capacitor sync output")
    # the native app's own code and the web sources are not copies
    for rel in ("src/battery.ts", "android/app/src/main/java/com/example/app/MainActivity.java", "ios/App/App/AppDelegate.swift"):
        assert clf.lookup(rel) is None, rel
    g = clf.summary()
    assert {c["target"]: c["source"] for c in g["copies"]}["android/app/src/main/assets/public"] == "dist"
    assert g["by_reason"]["copy of dist/ (Capacitor webDir)"] == 2      # source files only (the .js copies)


def test_capacitor_in_a_subdirectory_and_ignored_web_dir(tmp_path):
    clf = classify(tmp_path, {
        "apps/mobile/capacitor.config.ts": "export default { appId: 'a.b', webDir: 'www' }\n",
        "apps/mobile/.gitignore": "node_modules\n/www\n",
        "apps/mobile/www/main.js": "x\n",
        "apps/mobile/ios/App/App/public/main.js": "x\n",
        "apps/web/src/main.ts": "export const m = 1\n",
    })
    assert clf.lookup("apps/mobile/ios/App/App/public/main.js")["copy_of"] == "apps/mobile/www/main.js"
    assert reason(clf, "apps/mobile/www/main.js") == ("generated", "web build output (Capacitor webDir)")
    assert clf.lookup("apps/web/src/main.ts") is None


def test_capacitor_web_dir_written_by_angular(tmp_path):
    clf = classify(tmp_path, {"capacitor.config.json": '{"webDir": "www"}', "www/main.js": "x\n",
                              "angular.json": '{"projects": {"app": {"architect": {"build": {"options": {"outputPath": "www"}}}}}}',
                              "src/main.ts": "export const m = 1\n"})
    assert reason(clf, "www/main.js") == ("generated", "web build output (Capacitor webDir)")
    assert clf.lookup("src/main.ts") is None


def test_capacitor_web_dir_kept_when_it_is_source(tmp_path):
    clf = classify(tmp_path, {"capacitor.config.json": '{"webDir": "www"}', "www/app.js": "x\n"})
    assert clf.lookup("www/app.js") is None


def test_cordova_platform_www(tmp_path):
    clf = classify(tmp_path, {
        "config.xml": '<?xml version="1.0"?>\n<widget id="io.x" version="1.0.0" xmlns="http://www.w3.org/ns/widgets"></widget>\n',
        "www/js/index.js": "x\n",
        "platforms/android/app/src/main/assets/www/js/index.js": "x\n",
        "platforms/ios/www/js/index.js": "x\n",
    })
    assert clf.lookup("www/js/index.js") is None
    h = clf.lookup("platforms/ios/www/js/index.js")
    assert h["kind"] == "copied" and h["copy_of"] == "www/js/index.js"
    assert clf.lookup("platforms/android/app/src/main/assets/www/js/index.js")["copy_of"] == "www/js/index.js"


def test_openapi_generator_files(tmp_path):
    clf = classify(tmp_path, {
        "client/.openapi-generator/FILES": "README.md\nlib/api.dart\nlib/model/pet.dart\n",
        "client/.openapi-generator/VERSION": "7.0.0\n",
        "client/lib/api.dart": "class Api {}\n",
        "client/lib/model/pet.dart": "class Pet {}\n",
        "client/lib/extra.dart": "class Extra {}\n",        # added by hand (not in FILES)
    })
    assert reason(clf, "client/lib/api.dart") == ("generated", "OpenAPI Generator (.openapi-generator/FILES)")
    assert reason(clf, "client/lib/model/pet.dart")[0] == "generated"
    assert clf.lookup("client/lib/extra.dart") is None


# ------------------------------------------------------------------------------------------- .cg.yaml
def test_config_rules_and_validation(tmp_path):
    cfg = CFG.parse({"generated": {"paths": ["src/gen/**"], "vendored": ["libs/**"], "keep": ["src/gen/hand.ts", "src/x_pb2.py"],
                                   "include": False}})
    clf = classify(tmp_path, {"src/gen/a.ts": "x\n", "src/gen/hand.ts": "x\n", "libs/z.js": "x\n", "src/x_pb2.py": "x = 1\n"}, cfg)
    assert reason(clf, "src/gen/a.ts") == ("generated", ".cg.yaml generated.paths")
    assert reason(clf, "libs/z.js") == ("vendored", ".cg.yaml generated.vendored")
    assert clf.lookup("src/gen/hand.ts") is None and clf.lookup("src/x_pb2.py") is None
    for bad, msg in [({"generated": {"include": "yes"}}, "generated.include: expected true or false"),
                     ({"generated": {"paths": ["../x"]}}, "must stay inside the indexed root"),
                     ({"generated": {"skip": ["x"]}}, "unknown key 'skip'")]:
        with pytest.raises(CFG.ConfigError, match=msg):
            CFG.parse(bad)


def test_path_rules_consult_the_classifier(tmp_path):
    clf = classify(tmp_path, {"capacitor.config.json": '{"webDir": "dist"}', "ios/App/App/public/a.js": "x\n", "a_pb2.py": "x = 1\n"})
    r = PathRules(generated=clf)
    assert r.excluded("a_pb2.py") and r.excluded("ios/App/App/public/a.js") and not r.excluded("b.py")
    assert not r.excluded("a_pb2.py", generated=False)
    assert r.skip("ios/App/App", "public") and r.skip("", ".nuxt") and not r.skip("", "src")
    assert any("ios/App/App/public" in x for x in r.exclude_regex().split("|"))
    inc = G.Classifier(clf.root, include=True)
    assert not PathRules(generated=inc).excluded("a_pb2.py")


# ------------------------------------------------------------------------------------------- end to end
PY_APP = {
    "requirements.txt": "protobuf\n",
    "shop/__init__.py": "",
    "shop/orders_pb2.py": """
        # -*- coding: utf-8 -*-
        # Generated by the protocol buffer compiler.  DO NOT EDIT!
        from shop import service

        def decode(b):
            return service.place(b)
        """,
    "shop/schema.py": """
        # Code generated by schemagen. DO NOT EDIT.
        from shop import service

        def run():
            return service.place(1)
        """,
    "shop/service.py": """
        def place(order):
            return order
        """,
    "shop/api.py": """
        from shop import service

        def create(req):
            return service.place(req)
        """,
}


def test_default_index_has_no_generated_nodes_and_coverage_lists_them(tmp_path):
    root = write(tmp_path / "py", PY_APP)
    st = GraphStore(tmp_path / "py.db") if index_project(root, tmp_path / "py.db", "py") else None
    files = {r["file"] for r in st.q("SELECT DISTINCT file FROM nodes WHERE file IS NOT NULL")}
    assert "shop/service.py" in files and "shop/api.py" in files
    assert not files & {"shop/orders_pb2.py", "shop/schema.py"}
    callers = {c["fqn"] for c in Q.impact(st, "shop.service.place")["callers"]}
    assert callers == {"shop.api.create"}
    cov = C.for_graph(st)["py"]
    g = cov["generated"]
    assert g["mode"] == "excluded" and g["files"] == 2
    assert g["by_reason"] == {"protoc output (Python)": 1, "'Code generated ... DO NOT EDIT.' header": 1}
    py = next(e for e in cov["languages"] if e["language"] == "python")
    assert py["files"] == 3 and py.get("files_complete") is not False      # the 2 generated files are not "discovered"
    text = C.render(C.for_graph(st))
    assert "generated: 2 files excluded" in text and "shop/orders_pb2.py" in text
    assert "generated: 2 files excluded" in C.summary_line(cov)


def test_include_generated_labels_every_node(tmp_path):
    root = write(tmp_path / "py", PY_APP)
    stats = index_project(root, tmp_path / "py.db", "py", include_generated=True)
    assert stats["generated"]["mode"] == "indexed" and stats["generated"]["nodes_labelled"] > 0
    st = GraphStore(tmp_path / "py.db")
    rows = st.q("SELECT id, file, attrs FROM nodes WHERE file IN ('shop/orders_pb2.py', 'shop/schema.py')")
    assert rows and all(json.loads(r["attrs"])["generated"]["kind"] == "generated" for r in rows)
    assert not [r for r in st.q("SELECT attrs FROM nodes WHERE file = 'shop/service.py'") if r["attrs"] and "generated" in r["attrs"]]
    imp = Q.impact(st, "shop.service.place")
    by = {c["fqn"]: c for c in imp["callers"]}
    assert set(by) == {"shop.api.create", "shop.orders_pb2.decode", "shop.schema.run"}
    assert Q.caller_label(by["shop.orders_pb2.decode"]) == "  [generated: protoc output (Python)]"
    assert Q.caller_label(by["shop.api.create"]) == ""
    assert C.for_graph(st)["py"]["generated"]["mode"] == "indexed"
    out = cg("impact", "shop.service.place", "--db", tmp_path / "py.db").stdout
    assert "shop.schema.run  [generated: 'Code generated ... DO NOT EDIT.' header]" in out


def test_cli_flag_and_config_include(tmp_path):
    root = write(tmp_path / "py", {**PY_APP, ".cg.yaml": "generated:\n  include: true\n"})
    index_project(root, tmp_path / "a.db", "py")
    assert GraphStore(tmp_path / "a.db").q("SELECT count(*) c FROM nodes WHERE file = 'shop/schema.py'")[0]["c"] > 0
    (root / ".cg.yaml").unlink()
    r = cg("index", root, "--db", tmp_path / "b.db", "--include-generated")
    assert r.returncode == 0, r.stderr
    assert json.loads(r.stdout)["include_generated_flag"] is True
    assert "generated: 2 files indexed" in r.stderr
    show = cg("config", "show", root, "--include-generated").stdout
    assert "generated.include" in show and "flag --include-generated" in show


@pytest.mark.skipif(not HAS_NODE, reason="node + the TS extractor are needed")
def test_typescript_generated_client_and_capacitor_copy(tmp_path):
    files = {
        "package.json": '{"name": "app", "dependencies": {"express": "^4", "@capacitor/core": "^6"}}\n',
        "tsconfig.json": '{"compilerOptions": {"allowJs": true, "module": "commonjs"}}\n',
        "capacitor.config.json": '{"appId": "com.example.app", "webDir": "www"}\n',
        "web/api/client.ts": """
            /* @generated by an API client generator */
            export function fetchOrders() { return fetch('/api/orders') }
            """,
        "web/orders.ts": """
            import { fetchOrders } from './api/client'
            export function loadOrders() { return fetchOrders() }
            """,
        "web/index.ts": """
            import { loadOrders } from './orders'
            export function main() { return loadOrders() }
            """,
        "www/app.js": "function boot() { return 1 }\nmodule.exports = { boot }\n",
        "android/app/src/main/assets/public/app.js": "function boot() { return 1 }\nmodule.exports = { boot }\n",
    }
    root = write(tmp_path / "ts", files)
    index_project(root, tmp_path / "ts.db", "ts")
    st = GraphStore(tmp_path / "ts.db")
    files_in = {r["file"] for r in st.q("SELECT DISTINCT file FROM nodes WHERE file IS NOT NULL")}
    assert "web/orders.ts" in files_in
    assert "web/api/client.ts" not in files_in
    assert not any(f.startswith("android/") for f in files_in)
    g = C.for_graph(st)["ts"]["generated"]
    assert g["by_reason"] == {"@generated header": 1, "copy of www/ (Capacitor webDir)": 1}
    assert g["copies"][0]["target"] == "android/app/src/main/assets/public" and g["copies"][0]["source"] == "www"
    # included: every node from those files is labelled, and the copied module points to its source
    index_project(root, tmp_path / "inc.db", "ts", include_generated=True)
    st = GraphStore(tmp_path / "inc.db")
    rows = st.q("SELECT id, file, attrs FROM nodes WHERE file IN ('web/api/client.ts', 'android/app/src/main/assets/public/app.js')")
    assert {r["file"] for r in rows} == {"web/api/client.ts", "android/app/src/main/assets/public/app.js"}
    assert all(json.loads(r["attrs"])["generated"] for r in rows)
    cp = [r for r in rows if r["file"].startswith("android/") and r["id"].startswith("module:")]
    assert json.loads(cp[0]["attrs"])["generated"]["copy_of"] == "www/app.js"
    e = st.q("SELECT src, dst FROM edges WHERE kind = 'COPY_OF'")
    assert [(r["src"], r["dst"]) for r in e] == [(cp[0]["id"], "module:www/app.js")]


@pytest.mark.skipif(not HAS_NODE, reason="node + the TS extractor are needed")
def test_index_stats_count_the_classified_files(tmp_path):
    """stats.generated.files is the coverage count: TS / Dart files the extractors skip before parsing count too."""
    root = write(tmp_path / "shop", {
        "package.json": '{"name": "shop-web", "dependencies": {"axios": "^1"}}\n',
        "tsconfig.json": '{"compilerOptions": {"allowJs": true, "module": "commonjs"}}\n',
        "src/api/.openapi-generator/FILES": "api.ts\nmodels/order.ts\n",
        "src/api/api.ts": "export function listOrders() { return fetch('/api/orders') }\n",
        "src/api/models/order.ts": "export interface Order { id: number }\n",
        "src/orders.ts": "import { listOrders } from './api/api'\nexport function load() { return listOrders() }\n",
        "pubspec.yaml": "name: shop_app\nenvironment:\n  sdk: '>=3.0.0 <4.0.0'\n",
        "lib/user.dart": "part 'user.g.dart';\nclass User { final String name; User(this.name); }\n",
        "lib/user.g.dart": "// GENERATED CODE - DO NOT MODIFY BY HAND\npart of 'user.dart';\n"
                           "User _$UserFromJson(Map<String, dynamic> j) => User(j['name']);\n",
        "lib/main.dart": "import 'user.dart';\nvoid main() { print(User('a').name); }\n",
    })
    stats = index_project(root, tmp_path / "shop.db", "shop")
    g = stats["generated"]
    cov = C.for_graph(GraphStore(tmp_path / "shop.db"))["shop"]["generated"]
    assert g["files"] == cov["files"] == 3
    assert g["by_language"] == {"typescript": 2, "dart": 1}
    assert g["by_reason"] == cov["by_reason"] == {"OpenAPI Generator (.openapi-generator/FILES)": 2,
                                                  "build_runner output (*.g.dart)": 1}
    assert g["mode"] == "excluded" and g["files_with_dropped_nodes"] <= g["files"]
    stats = index_project(root, tmp_path / "inc.db", "shop", include_generated=True)
    assert stats["generated"]["files"] == 3 and stats["generated"]["mode"] == "indexed"
    assert "files_with_nodes" in stats["generated"]
