<?php

use App\Http\Controllers\AfterWriteController;
use App\Http\Controllers\ConditionalController;
use App\Http\Controllers\DeepController;
use App\Http\Controllers\DenyController;
use App\Http\Controllers\FalseGuardController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\HasMwController;
use App\Http\Controllers\InvokeMwController;
use App\Http\Controllers\MwController;
use App\Http\Controllers\OrderResourceController;
use App\Http\Controllers\PolicyController;
use App\Http\Controllers\ShipmentController;
use App\Http\Controllers\RefundController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SecretCompareController;
use App\Http\Controllers\TraitController;
use App\Http\Controllers\WarehouseSyncController;
use Illuminate\Support\Facades\Route;

Route::post('orders/{order}/refund', [RefundController::class, 'store']);
Route::post('warehouse/sync', WarehouseSyncController::class);
Route::post('orders/{order}/policy', [PolicyController::class, 'update']);
Route::post('orders/{order}/gate', [PolicyController::class, 'gate']);
Route::post('orders/{order}/denies', [PolicyController::class, 'denies']);
Route::post('orders/{order}/maybe', [ConditionalController::class, 'update']);
Route::post('mw/show', [MwController::class, 'show']);
Route::delete('mw/show', [MwController::class, 'destroy']);
Route::get('has/show', [HasMwController::class, 'show']);
Route::get('has/index', [HasMwController::class, 'index']);
Route::post('orders/{order}/trait', [TraitController::class, 'update']);
Route::post('orders/{order}/plain', [TraitController::class, 'plain']);
Route::post('deep/ok', [DeepController::class, 'ok']);
Route::post('deep/late', [DeepController::class, 'late']);
Route::post('orders/{order}/after', [AfterWriteController::class, 'update']);
Route::post('orders/{order}/form', [FormController::class, 'update']);
Route::post('orders/{order}/open', [FormController::class, 'open']);
Route::post('staff/role', [RoleController::class, 'update']);
Route::post('sync/compare', [SecretCompareController::class, 'store']);
Route::post('orders/{order}/deny', [DenyController::class, 'update']);
Route::post('orders/{order}/ignored', [FalseGuardController::class, 'ignored']);
Route::post('orders/{order}/allows', [FalseGuardController::class, 'allows']);
Route::post('orders/{order}/allows-return', [FalseGuardController::class, 'allowsReturn']);
Route::post('orders/{order}/allows-abort', [FalseGuardController::class, 'allowsAbort']);
Route::post('orders/{order}/ui', [FalseGuardController::class, 'ui']);
Route::post('orders/{order}/flag', [FalseGuardController::class, 'flag']);
Route::post('orders/{order}/preview', [FalseGuardController::class, 'preview']);
Route::post('orders/{order}/after-callee', [FalseGuardController::class, 'afterCallee']);
Route::post('orders/{order}/branched', [FalseGuardController::class, 'branched']);
Route::post('orders/{order}/branch-call', [FalseGuardController::class, 'branchCall']);
Route::post('orders/{order}/gated', [FalseGuardController::class, 'gated']);
Route::post('sync/headers', [FalseGuardController::class, 'headers']);
Route::post('sync/loose', [FalseGuardController::class, 'loose']);
Route::resource('orders', OrderResourceController::class);
Route::apiResource('shipments', ShipmentController::class);
Route::post('invoke/sync', InvokeMwController::class);
