// generated by graphql-codegen
import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';

export const AuthorDocument = gql`
  query Author($id: ID!) {
    author(id: $id) {
      id
      name
    }
  }
`;

export function useAuthorQuery(baseOptions) {
  return Apollo.useQuery(AuthorDocument, baseOptions);
}

export function useAuthorLazyQuery(baseOptions) {
  return Apollo.useLazyQuery(AuthorDocument, baseOptions);
}
