// Generated by auto imports (hand-written copy of the shape `nuxi prepare` generates, so the sample needs no install)
export {}
declare global {
  const useApi: typeof import('../../app/composables/useApi').useApi
  const useReports: typeof import('../../app/composables/useReports').useReports
  const formatMoney: typeof import('../../app/utils/money').formatMoney
  const useSessionStore: typeof import('../../app/stores/useSessionStore').useSessionStore
  const useRuntimeConfig: () => { public: Record<string, string> }
  const $fetch: <T = any>(url: string, opts?: { method?: string, query?: Record<string, unknown>, body?: unknown, baseURL?: string }) => Promise<T>
  const defineStore: <Id extends string, A>(id: Id, def: { actions: A & ThisType<A> }) => () => A
  const definePageMeta: (meta: { layout?: string, middleware?: string[] }) => void
}
